language: node_js
cache: npm

stages:
  - check

node_js:
  - '10'

os:
  - linux

jobs:
  include:
    - stage: check
      script:
        - npx aegir commitlint --travis
        - npx aegir dep-check
        - npm run lint

notifications:
  email: false
